### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by harshkumarkhatri** [shashikantdwivedi/W3schools-noAds#1]
When we have opened the app and the homepage has not loaded yet if we keep on clicking the home page it keeps on pushing the home page in the stack. For eg. if I have clicked 4 times on the home before it loads, so there will be home page stacked 4 times and that will also need to be loaded before the topmost pages are loaded which will consume more internet and could app a bit slower.

**Comment by shashikantdwivedi** [comment]
Thank You for reporting the problem. The issue has been fixed now
