### ISSUE TITLE
Refresh Page

### ISSUE THREAD

**Issue by harshkumarkhatri** [shashikantdwivedi/W3schools-noAds#3]
When I have clicked on the refresh icon how would I know that the page is refreshed if the home page is in its original state?
Original state here means:- App is opened and the home page is not scrolled or changed.<br>
The refresh icon stays black even after refreshing. Also, the user has no idea whether the page is refreshing as the app holds its state for a few seconds. It would be better if there is some animation and the home icon turns black once the refresh is completed.

**Comment by shashikantdwivedi** [comment]
Fixed the problem. Added a loading animating at the time of page loading or refreshing
